"""empty message

Revision ID: 152fb9734bbc
Revises: None
Create Date: 2016-12-21 19:46:13.250822

"""

# revision identifiers, used by Alembic.
revision = '152fb9734bbc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PictureDate',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Uuid', sa.String(length=32), nullable=True),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PictureDate')
    ### end Alembic commands ###
